services:
  contao_bootstrap.layout.view.template.filter.replace_css_classes:
    class: ContaoBootstrap\Layout\View\Template\ReplaceCssClassesFilter
    arguments:
      - "@=container.get('contao_bootstrap.config').get('layout.filters.replace_css_classes_templates')"
      - "@=container.get('contao_bootstrap.config').get('layout.replace_css_classes')"
    tags:
      - { name: contao_bootstrap.post_render_filter }

  contao_bootstrap.layout.view.template.filter.replace_image_classes:
    class: ContaoBootstrap\Layout\View\Template\ReplaceImageClassesFilter
    arguments:
      - "@=container.get('contao_bootstrap.config').get('layout.filters.replace_images_classes_templates')"
    tags:
      - { name: contao_bootstrap.pre_render_filter }

  contao_bootstrap.layout.view.template.filter.replace_table_classes:
    class: ContaoBootstrap\Layout\View\Template\ReplaceTableClassesFilter
    arguments:
      - "@=container.get('contao_bootstrap.config').get('layout.filters.replace_table_classes_templates')"
    tags:
      - { name: contao_bootstrap.pre_render_filter }

  contao_bootstrap.layout.listener.layout_dca:
    class: ContaoBootstrap\Layout\Listener\Dca\LayoutDcaListener
    arguments:
      - '@contao_bootstrap.config'
      - '@database_connection'
